<?php

namespace Dalmer\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CosmeticosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CosmeticosRepository extends EntityRepository
{
}