<?php

namespace Dalmer\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistribuidoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistribuidoresRepository extends EntityRepository
{
}